### ISSUE TITLE
Error: abort was called

### ISSUE THREAD

**Issue by abcdsxg** [chame1eon/jnitrace#4] opened 2019-09-09 12:27 UTC
`jnitrace -l libsgmainso-6.4.94.so com.alimama.moon`
get this error:

ERROR: {'type': 'error', 'description': 'Error: abort was called', 'stack': 'Error: abort was called\n    at InvocationContext.<anonymous> (jnitrace/src/jni/java_vm_interceptor.ts:100:40)', 'fileName': 'jnitrace/src/jni/java_vm_interceptor.ts', 'lineNumber': 100, 'columnNumber': 40}

**Comment by chame1eon** [comment] 2019-09-09 19:01
Thanks for your bug report. I was able to reproduce the same issue and discovered it was due to the library calling the DestroyJavaVM method on start up. Unfortunately, the application crash after this call is expected as the DestroyJavaVM method will call abort and stop execution.

I tried to have a quick look into the library to discover why it was calling DestroyJavaVM. It looked to me like the library code was obfuscated, so it will be a fair bit of effort to find where the DestroyJavaVM call is made. My assumption is that on start up that library detects frida or the tracing happening and calls DestroyJavaVM to abort execution.

Sorry I cannot be more help. If you do discover the steps to stop the anti-debugging then you can use --prepend-script to run a Frida script to disable it before jnitrace starts tracing.

**Comment by chame1eon** [comment] 2019-09-16 18:35
Closing this as it has been a week.

**Closed by chame1eon** 2019-09-16 18:35 UTC
