### ISSUE TITLE
not working on x86 emulator with arm support

### ISSUE THREAD

**Issue by qtfreet00** [chame1eon/jnitrace#6] opened 2019-10-21 07:24 UTC
I'm tested jnitrace on mumu emulator which support arm libraries 

jnitrace don't print anything

tested library is arm

**Comment by chame1eon** [comment] 2019-10-22 01:09
Thanks for the bug report. I think the issue is that Frida does not interception where ARM to x86 translation is taking place. jnitrace just uses Frida behind the scenes so if Frida is not working jnitrace will not work. Can you try seeing if Frida can hook some of the functions in that library?

**Comment by qtfreet00** [comment] 2019-10-22 02:24
yes，my other frida scripts works correctly on this emulator,and i tried jnitrace on my real phone,works well too , i think maybe jnitrace choose arch wrong on emulator run with arm library

**Comment by chame1eon** [comment] 2019-10-22 04:42
Okay, thanks for trying that. I will try to reproduce the issue to see if I can get to the bottom of it. Any chance you can send me a link to the APK you were using for testing?

**Comment by chame1eon** [comment] 2019-11-02 13:57
I have tested my own test application on MUMU emulator and jnitrace works fine if the application has x86 supported libraries. If it only has arm, like you say, it will not run. This is a common problem with native Frida on the x86 project emulators which MUMU emulator uses. Those emulators use the libhoudini library to dynamically translate ARM code into x86 instructions and that causes problems when trying to hook them with Frida. I am closing this issue now as it is not really a jnitrace issue, more a Frida/libhoudini issue. Thanks for your bug report.

**Closed by chame1eon** 2019-11-02 13:57 UTC
